# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PlayFootBall' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!


  target 'PlayFootBallTests' do
    inherit! :search_paths
    # Pods for testing
  end

   target 'PlayFootBallUITests' do
    inherit! :search_paths
    # Pods for testing
  end


pod 'WechatOpenSDK'
pod 'YYKit'
pod 'MJExtension'
pod 'Masonry'
pod 'MJRefresh'
pod 'Toast'
pod 'IQKeyboardManager'
pod 'Reachability'
pod 'DZNEmptyDataSet'
pod 'SVProgressHUD'
pod 'RKNotificationHub'
pod 'LCActionSheet'
pod 'SDWebImage/GIF'
pod 'AFNetworking'
pod 'FLAnimatedImage'
pod 'SDCycleScrollView'
end

